# Copyright 2012 Google Inc. All Rights Reserved.

__author__ = 'benvanik@google.com (Ben Vanik)'


# An ordered list of all CSS files used by the client game
file_set(
    name='all_client_css',
    srcs=[
        'common.gss',
        'font-monospace.gss',
        'alert-assets.gss',
        'alerts.gss',
        ])
